version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing Dependencies
      - npm ci
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build